from CustomError import CustomError

class validationError(CustomError):
    pass

    def print(self):
        print('student not found !!!')

    